import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";

import "./globals.css";
import "swiper/css";
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';

import { ThemeProvider } from "@/context/theme";
import { ImagesProvider } from "@/context/images";
import { NavbarComponent } from "@/components/web/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s - Raqamli Gallereya",
    default: "Raqamli Gallereya",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale || "uz"}>
      <head>
        <link rel="stylesheet" href="/fonts/WhyteInktrap/stylesheet.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <NextIntlClientProvider>
          <ThemeProvider>
            <ImagesProvider>
              <NavbarComponent />
              {children}
            </ImagesProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
